# -*- coding: utf-8 -*-
"""Sheth L.U.J & Sir M.V College

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mLpvzqD-DD7CHqH8KSzgnhLjVWyQJK4k

PRACTICAL 2 B,C             Data Science

T096 Siddhi Naik
"""

#data wrangling
import pandas as pd
dataframe = pd.DataFrame()

"""Describing the data"""

import pandas as pd
from google.colab import files

uploaded = files.upload()


df = pd.read_csv("Titanic-Dataset.csv")
df.head(2)
print("Dimensions:{}".format(df.shape))
df.describe()

"""navigating Dataframe"""

#select first row
print(df.iloc[0])
#select 3 rows
print(df.iloc[1:4])
#all rows up to and inculding the fourth row
print(df.iloc[:4])

df = df.set_index(df['Name'])
df.loc['Heikkinen, Miss. Laina']

"""selecting rows based on conditionals"""

df[df['Sex'] == 'female'].head(2)

"""Replacing values"""

df['Sex'].replace('female','Woman').head(2)

df['Sex'].replace(['female','male'],['Woman','Man']).head(5)

df.replace(1,"One").head(2)

"""Renaming colums"""

df.rename(columns={'PClass': 'Passenger Class'}).head(2)

df.rename(columns={'PClass': 'Passenger Class','Sex':'Gender'}).head(2)



"""finding the min,max,sum, avg,count"""

print('Maximum: {}'.format(df['Age'].max()))
print('Minimum: {}'.format(df['Age'].min()))
print('Mean: {}'.format(df['Age'].mean()))
print('Sum: {}'.format(df['Age'].sum()))
print('Count: {}'.format(df['Age'].count()))

print("Variance: {}".format(df['Age'].var()))
print("Standard Deviation: {}".format(df['Age'].std()))
print("Kurtosis: {}".format(df['Age'].kurt()))
print("Skewness: {}".format(df['Age'].skew()))

"""Finding unique values"""

unique_sex = df['Sex'].unique()
print(unique_sex)

sex_counts = df['Sex'].value_counts()
print(sex_counts)

"""handling missing values"""

missing_ages = df[df['Age'].isnull()].head(2)
print(missing_ages)

"""deleting a column"""

df_without_age = df.drop('Age', axis=1)
print(df_without_age.head(2))



"""deleting a row"""

df[df['Name'] != 'Male'].head(2)

#deleting a row by matching unique value
df[df['Name']!= 'Braund, Mr. Owen Harris'].head(2)

df[df.index != 1].head(2)

"""Grouping rows by values

"""

df.groupby('Sex').mean(numeric_only=True)

df.groupby('Survived')['Name'].count()

df.groupby(['Sex','Survived'])['Age'].mean()

"""looping over a colum"""

for name in df['Name'][0:2]:
  print(name.upper())

[name.upper() for name in df['Name'][0:2]]

"""applying fun over all element in col"""

def uppercase(x):
  return x.upper()
df['Name'].apply(uppercase)[0:2]

"""applying fun to grp"""

df.groupby('Sex').apply(lambda x: x.count())

"""concating dataframes"""

