# -*- coding: utf-8 -*-
"""Sheth L.U.J & Sir M.V College

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ijZ55iS_eRMYueTEA9ry5JpT8t7x07Ff

PRACTICAL 2 A                          DATA SCIENCE

T096 siddhi naik

Loading a Sample Dataset
"""

from sklearn import datasets
digits = datasets.load_digits()

features = digits.data
target = digits.target
features[0]



creating stimulated datasets

from sklearn.datasets import make_regression
features,target,coefficients = make_regression(n_samples = 50,
                                               n_features=3,
                                               n_informative=3,
                                               n_targets = 1,
                                               noise = 0.0,
                                               coef = True,
                                               random_state = 2)
print("feature matrix \n{}".format(features[:4]))
print("target vector \n{}".format(target[:3]))

classification

from sklearn.datasets import make_classification
features,target = make_classification(n_samples = 50,
                                               n_features=3,
                                               n_informative=3,
                                               n_redundant=0,
                                               n_classes =2,
                                               weights = [.25,.75],
                                               random_state = 2)
print("feature matrix \n{}".format(features[:4]))
print("target vector \n{}".format(target[:3]))

"""blobs"""

from sklearn.datasets import make_blobs
features, target = make_blobs(n_samples= 50,
                              n_features = 3,
                              centers = 3,
                              cluster_std = 0.5,
                              shuffle = True,
                              random_state = 1)
print("feature matrix \n{}".format(features[:4]))
print("target vector \n{}".format(target[:3]))

import matplotlib.pyplot as plt
plt.scatter(features[:,0], features[:,1], c= target)
plt.show()

"""loading a csv file"""

from google.colab import files
import pandas as pd
uploaded = files.upload()


df = pd.read_csv('industry.csv')

df.head(3)

import pandas as pd
from google.colab import files
uploaded = files.upload()


df = pd.read_excel('file_example_XLS_10.xls')

df.head(3)

import pandas as pd

from google.colab import files
uploaded = files.upload()


df = pd.read_json("mtcars.json", lines=True)
df.head(2)

import pandas as pd
from sqlalchemy import create_engine

df = pd.read_csv("Iris.csv")

db_connection = create_engine('sqlite:///iris.db')



df_from_db = pd.read_sql_query('SELECT * FROM iris', db_connection)


df_from_db.head()